### ISSUE TITLE
龟骨网站搭建项目 寒假计划

### ISSUE THREAD

**Issue by FS-tar** [smu-guigu/smu-guigu.github.io#7]
# 一 1.16——1.20
1. 在本地部署龟骨网站。要求达到如下效果（127.0.0.1代表本机，即不用联网也能通过本机访问网站）：
  ![image](https://github.com/smu-guigu/smu-guigu.github.io/assets/119573640/14979b4f-df74-46e6-aa52-d3fd6c857a84)
2. 熟悉**命令行环境**以及**部分常用指令**。根据 b 站教程下载 Git，通过 Git Bash 尝试以下命令（图方便也可以使用 powershell，但二者都不及真实的 Linux 命令行）：
    -  pwd - print name of working directory
    - ls - list directory contents
    - cd - change directory
    - mkdir - make directories
    - rmdir - remove empty directories
    - cp - copy files and directories
    - mv - move (rename) files
    - vim  - Vi IMproved, a programmer's text editor

    目标：编写一个用于打印“hello world”的 C 语言程序并保存（不用执行）。

3. 熟悉 Linux 系统（依赖 2）。通过虚拟机（推荐 [WSL](https://learn.microsoft.com/zh-cn/windows/wsl/install)）或 Docker 或者云服务器等，接触 Linux 系统，目标：在 Linux 平台下用 C 语言编写一个打印“hello world”的程序并执行。

**Comment by mengyetianxing** [comment]
收到

**Comment by lasermanta** [comment]
收到

**Comment by FS-tar** [comment]
###  **二 1.21--1.28**
1.  了解域名解析，域名结构以及服务器相关知识。学习如何在腾讯云，阿里云或其它官方申请域名。
2. 搭建静态网站，上传至GitHub。自行进行仿站学习，要求网站实现手机可预览，图标，2D/3D动画，简易的搜索引擎。
 （多样式风格展现网站，下周会议统一展示，有几率写进大创项目周记录，内容不定但别太离谱）
3. 提前学习数据库知识

**Comment by bakayy** [comment]
收到
